#include "pf.h"
#include <stdio.h>
#include <string.h>
int main() {
PF_Init();
int fd, pagenum;
char* pagebuf;
PFRAID_buf_ele * ptr;
PF_CreateFile("abc");
fd = PF_OpenFile("abc");
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_CloseFile(fd);
PF_CreateFile("def");
fd = PF_OpenFile("def");
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_CloseFile(fd);
PF_CreateFile("ghi");
fd = PF_OpenFile("ghi");
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_CloseFile(fd);
PF_CreateFile("jkl");
fd = PF_OpenFile("jkl");
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_CloseFile(fd);
PF_CreateFile("mno");
fd = PF_OpenFile("mno");
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_AllocPage(fd, &pagenum, &pagebuf);
memset(pagebuf, 'a', PF_PAGE_SIZE);
PF_UnfixPage(fd, pagenum, 1);
PF_CloseFile(fd);
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
PF_TakeSnapshot("abc");
PF_TakeSnapshot("def");
PF_TakeSnapshot("ghi");
PF_TakeSnapshot("jkl");
PF_TakeSnapshot("mno");
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
stepTime();
return 0;
}
